"""
lx06_tool/modules/usb_scanner.py
----------------------------------
Phase 1: udev rules installation and USB handshake orchestration.

The Amlogic AXG (LX06) enters USB burning mode for approximately 2 seconds
after power-on with the test-pad shorted. We poll `update identify` at 100 ms
intervals to catch this window.
"""

from __future__ import annotations

import asyncio
import time
from pathlib import Path
from typing import Callable, Optional

from lx06_tool.constants import (
    HANDSHAKE_DEFAULT_TIMEOUT_S,
    HANDSHAKE_POLL_INTERVAL_S,
    UDEV_RULE_LINE,
    UDEV_RULES_DEST,
)
from lx06_tool.exceptions import (
    DeviceDisconnectedError,
    HandshakeTimeoutError,
    UdevRulesError,
)
from lx06_tool.utils.amlogic import AmlogicDeviceInfo, AmlogicTool
from lx06_tool.utils.runner import run


# ─── udev Rules ───────────────────────────────────────────────────────────────

UDEV_RULE_CONTENT = f"""\
# Amlogic USB burning mode — LX06 flash tool
# Generated by lx06-flash-tool
{UDEV_RULE_LINE}
"""


async def install_udev_rules(
    dest: str = UDEV_RULES_DEST,
    *,
    sudo_password: str = "",
) -> None:
    """
    Write the Amlogic udev rule and reload the rule database.

    Strategy: write content to a temp file first, then sudo cp it to
    the destination. This avoids stdin conflicts between sudo -S
    (password on stdin) and tee (file content on stdin).
    """
    import tempfile
    dest_path = Path(dest)

    # Write rules to a temp file first (no sudo needed)
    with tempfile.NamedTemporaryFile(mode="w", suffix=".rules", delete=False) as tmp:
        tmp.write(UDEV_RULE_CONTENT)
        tmp_path = tmp.name

    try:
        # Copy temp file to destination with sudo
        if sudo_password:
            copy = await run(
                ["sudo", "-S", "cp", tmp_path, str(dest_path)],
                stdin_data=sudo_password + "\n",
                timeout=10,
            )
        else:
            copy = await run(
                ["sudo", "cp", tmp_path, str(dest_path)],
                timeout=10,
            )
        if copy.returncode != 0:
            raise UdevRulesError(
                f"Failed to write udev rules to {dest_path}:\n{copy.stderr}"
            )
    finally:
        Path(tmp_path).unlink(missing_ok=True)

    # Reload and trigger (works on all modern systemd distros)
    for cmd in (
        ["udevadm", "control", "--reload-rules"],
        ["udevadm", "trigger", "--subsystem-match=usb"],
    ):
        if sudo_password:
            result = await run(
                ["sudo", "-S"] + cmd,
                stdin_data=sudo_password + "\n",
                timeout=15,
            )
        else:
            result = await run(["sudo"] + cmd, timeout=15)
        if result.returncode != 0:
            raise UdevRulesError(
                f"udevadm failed: sudo {' '.join(cmd)}\n{result.stderr}"
            )

def udev_rules_installed(dest: str = UDEV_RULES_DEST) -> bool:
    """Return True if the udev rules file already exists."""
    return Path(dest).exists()


# ─── USB Handshake Loop ───────────────────────────────────────────────────────

async def handshake_loop(
    tool: AmlogicTool,
    *,
    timeout: int = HANDSHAKE_DEFAULT_TIMEOUT_S,
    poll_interval: float = HANDSHAKE_POLL_INTERVAL_S,
    on_attempt: Optional[Callable[[int, int], None]] = None,
) -> AmlogicDeviceInfo:
    """
    Poll `update identify` every `poll_interval` seconds until the device
    responds or `timeout` seconds elapse.

    Parameters
    ----------
    tool         : Initialised AmlogicTool instance.
    timeout      : Total seconds before giving up.
    poll_interval: Seconds between polls (default 100 ms).
    on_attempt   : Called with (attempt_number, elapsed_seconds) each poll.

    Returns
    -------
    AmlogicDeviceInfo on success.

    Raises
    ------
    HandshakeTimeoutError if the device is not identified within `timeout`.
    """
    start = time.monotonic()
    attempt = 0

    while True:
        elapsed = int(time.monotonic() - start)
        if elapsed >= timeout:
            raise HandshakeTimeoutError(timeout)

        attempt += 1
        if on_attempt:
            on_attempt(attempt, elapsed)

        try:
            info = await tool.identify(timeout=2)
            if info.identified:
                return info
        except Exception:
            # identify() can raise on USB errors — keep looping
            pass

        await asyncio.sleep(poll_interval)


# ─── Disconnect Detection ─────────────────────────────────────────────────────

async def wait_for_disconnect(
    tool: AmlogicTool,
    *,
    check_interval: float = 1.0,
    timeout: int = 30,
) -> None:
    """
    Poll until the device stops responding to `identify`.
    Useful for detecting safe removal after a flash operation.

    Raises DeviceDisconnectedError if still connected after `timeout`.
    """
    start = time.monotonic()
    while time.monotonic() - start < timeout:
        try:
            info = await tool.identify(timeout=2)
            if not info.identified:
                return
        except Exception:
            return  # Exception = device gone = success
        await asyncio.sleep(check_interval)

    raise DeviceDisconnectedError(
        f"Device still connected after {timeout}s — expected disconnection."
    )
